export const SET_ACTIVE_CITY = "SET_ACTIVE_CITY";
export const LOAD_MORE_PROPERTIES = "LOAD_MORE_PROPERTIES";
export const SET_SELECTED_PROPERTY = "SET_SELECTED_PROPERTY";
export const RESET_ITEMS_TO_SHOW = "RESET_ITEMS_TO_SHOW";