const data = [
  {
    id: 1,
    location: "123 Main St",
    name: "Cozy Inn",
    popular: true,
    facility: { rooms: 4, beds: 6, bathrooms: 2, sqft: 1200 },
    rent: 1500,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259314/hotels/light-garden-luxury-pool-nature_1203-4908_cmraeb.jpg",
    city: "New York",
  },
  {
    id: 2,
    location: "456 Elm Ave",
    name: "Riverside Lodge",
    popular: false,
    facility: { rooms: 3, beds: 4, bathrooms: 1, sqft: 900 },
    rent: 1100,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259308/hotels/swimming-pool-beach-luxury-hotel-type-entertainment-complex-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-turkey_146671-18726_kcljqm.jpg",
    city: "Mumbai",
  },
  {
    id: 3,
    location: "789 Oak Dr",
    name: "Green Valley Retreat",
    popular: true,
    facility: { rooms: 5, beds: 8, bathrooms: 3, sqft: 1600 },
    rent: 2000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259288/hotels/relax-area-resort_1150-10728_wnpqfl.jpg",
    city: "Paris",
  },
  {
    id: 4,
    location: "101 Pine Lane",
    name: "Sunny Side Motel",
    popular: false,
    facility: { rooms: 2, beds: 2, bathrooms: 1, sqft: 600 },
    rent: 800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259280/hotels/leisure-beautiful-health-garden-landscape_1203-4856_ct2gke.jpg",
    city: "London",
  },
  {
    id: 5,
    location: "222 Cedar St",
    name: "Mountain View Lodge",
    popular: true,
    facility: { rooms: 6, beds: 10, bathrooms: 4, sqft: 2200 },
    rent: 2800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306721/hotels/popular-resort-amara-dolce-vita-luxury-hotel-with-pools-water-parks-recreational-area-along-sea-coast-turkey-tekirova-kemer_146671-18757_dxdfpl.jpg",
    city: "New York",
  },
  {
    id: 6,
    location: "Lakeside Cottage",
    name: "Lakeside Cottage",
    popular: false,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306715/hotels/sky-pool-background-swimming-travel_1203-4947_suxxt5.jpg",
    city: "Mumbai",
  },
  {
    id: 7,
    location: "Beachfront Bungalow",
    name: "Beachfront Bungalow",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1200 },
    rent: 1600,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306709/hotels/decorative-wooden-jacht-stands-before-picture-sea-port-wall_1304-3691_rsvxba.jpg",
    city: "Paris",
  },
  {
    id: 8,
    location: "Mountain Retreat",
    name: "Mountain Retreat",
    popular: false,
    facility: { rooms: 4, beds: 8, bathrooms: 2, sqft: 1600 },
    rent: 2000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306702/hotels/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-luxury-hotel-resort_146671-18827_c1bjuq.jpg",
    city: "London",
  },
  {
    id: 9,
    location: "City Center Apartment",
    name: "City Center Apartment",
    popular: true,
    facility: { rooms: 1, beds: 2, bathrooms: 1, sqft: 500 },
    rent: 1200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306697/hotels/pool-relaxation-sea-scene-nature_1203-6304_rb6iqq.jpg",
    city: "New York",
  },
  {
    id: 10,
    location: "Luxury Suite",
    name: "Luxury Suite",
    popular: true,
    facility: { rooms: 5, beds: 10, bathrooms: 4, sqft: 2500 },
    rent: 3500,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306693/hotels/swimming-pool_1203-3484_zbync2.jpg",
    city: "Mumbai",
  },
  {
    id: 11,
    location: "Lakefront Lodge",
    name: "Lakefront Lodge",
    popular: true,
    facility: { rooms: 4, beds: 8, bathrooms: 3, sqft: 1800 },
    rent: 2200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306687/hotels/admiralty-embankment-night_1398-2738_pw0pcc.jpg",
    city: "Paris",
  },
  {
    id: 12,
    location: "Downtown Loft",
    name: "Downtown Loft",
    popular: false,
    facility: { rooms: 1, beds: 1, bathrooms: 1, sqft: 400 },
    rent: 800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306681/hotels/relaxation-pool-umbrella-lounge-sky_1203-4625_bteahn.jpg",
    city: "London",
  },
  {
    id: 13,
    location: "Seaside Retreat",
    name: "Seaside Retreat",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1300 },
    rent: 1700,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306674/hotels/night-city-view_1417-1724_e7ncnb.jpg",
    city: "New York",
  },
  {
    id: 14,
    location: "Mountain Cabin",
    name: "Mountain Cabin",
    popular: false,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306670/hotels/night-view-skyscraper-port-olimpic_1398-428_yr8yyf.jpg",
    city: "Mumbai",
  },
  {
    id: 15,
    location: "Riverside Cottage",
    name: "Riverside Cottage",
    popular: true,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 700 },
    rent: 950,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306665/hotels/hotel-nevada-usa_1268-14393_gu9wbb.jpg",
    city: "Paris",
  },
  {
    id: 16,
    location: "Coastal Villa",
    name: "Coastal Villa",
    popular: true,
    facility: { rooms: 5, beds: 8, bathrooms: 3, sqft: 1600 },
    rent: 2100,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306658/hotels/popular-resort-amara-dolce-vita-luxury-hotel-with-pools-water-parks-recreational-area-along-sea-coast-turkey-sunset-tekirova-kemer_146671-18759_g4jziy.jpg",
    city: "London",
  },
  {
    id: 17,
    location: "Downtown Penthouse",
    name: "Downtown Penthouse",
    popular: false,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1400 },
    rent: 1900,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306650/hotels/large-pool-with-umbrellas-hammocks_1203-182_qwp4as.jpg",
    city: "New York",
  },
  {
    id: 18,
    location: "Lakeview Chalet",
    name: "Lakeview Chalet",
    popular: true,
    facility: { rooms: 4, beds: 6, bathrooms: 2, sqft: 1500 },
    rent: 1800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306645/hotels/swimming-pool_74190-1977_dsxu2o.jpg",
    city: "Mumbai",
  },
  {
    id: 19,
    location: "Beach House",
    name: "Beach House",
    popular: false,
    facility: { rooms: 3, beds: 4, bathrooms: 2, sqft: 1200 },
    rent: 1600,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306638/hotels/colonial-style-house-night-scene_1150-17925_dww47k.jpg",
    city: "Paris",
  },
  {
    id: 20,
    location: "Urban Condo",
    name: "Urban Condo",
    popular: true,
    facility: { rooms: 2, beds: 2, bathrooms: 1, sqft: 700 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306631/hotels/urban-city-architecture_649448-5343_zbklor.jpg",
    city: "London",
  },
  {
    id: 21,
    location: "Hillside Retreat",
    name: "Hillside Retreat",
    popular: true,
    facility: { rooms: 4, beds: 6, bathrooms: 2, sqft: 1400 },
    rent: 1800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306625/hotels/luxury-pool-villa-spectacular-contemporary-design-digital-art-real-estate-home-house-property-ge_1258-150759_gyiqec.jpg",
    city: "New York",
  },
  {
    id: 22,
    location: "Oceanfront Oasis",
    name: "Oceanfront Oasis",
    popular: false,
    facility: { rooms: 3, beds: 4, bathrooms: 2, sqft: 1100 },
    rent: 1500,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306618/hotels/glassclad-skyscrapers-central-mumbai-reflecting-sunset-hues-blue-hour_469504-15_lh7fmv.jpg",
    city: "Mumbai",
  },
  {
    id: 23,
    location: "Countryside Cottage",
    name: "Countryside Cottage",
    popular: true,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306610/hotels/swimming-pool_74190-2109_sjywzm.jpg",
    city: "Paris",
  },
  {
    id: 24,
    location: "Downtown Suite",
    name: "Downtown Suite",
    popular: false,
    facility: { rooms: 1, beds: 1, bathrooms: 1, sqft: 500 },
    rent: 900,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259314/hotels/light-garden-luxury-pool-nature_1203-4908_cmraeb.jpg",
    city: "London",
  },
  {
    id: 25,
    location: "Lakeview Cabin",
    name: "Lakeview Cabin",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1200 },
    rent: 1600,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259308/hotels/swimming-pool-beach-luxury-hotel-type-entertainment-complex-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-turkey_146671-18726_kcljqm.jpg",
    city: "New York",
  },
  {
    id: 26,
    location: "Rural Hideaway",
    name: "Rural Hideaway",
    popular: true,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 700 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259288/hotels/relax-area-resort_1150-10728_wnpqfl.jpg",
    city: "Mumbai",
  },
  {
    id: 27,
    location: "Beachfront Paradise",
    name: "Beachfront Paradise",
    popular: false,
    facility: { rooms: 4, beds: 8, bathrooms: 3, sqft: 1600 },
    rent: 2100,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259280/hotels/leisure-beautiful-health-garden-landscape_1203-4856_ct2gke.jpg",
    city: "Paris",
  },
  {
    id: 28,
    location: "Riverside Cabin",
    name: "Riverside Cabin",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1400 },
    rent: 1800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306721/hotels/popular-resort-amara-dolce-vita-luxury-hotel-with-pools-water-parks-recreational-area-along-sea-coast-turkey-tekirova-kemer_146671-18757_dxdfpl.jpg",
    city: "London",
  },
  {
    id: 29,
    location: "Urban Loft",
    name: "Urban Loft",
    popular: false,
    facility: { rooms: 2, beds: 2, bathrooms: 1, sqft: 650 },
    rent: 950,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306715/hotels/sky-pool-background-swimming-travel_1203-4947_suxxt5.jpg",
    city: "New York",
  },
  {
    id: 30,
    location: "Mountain Chalet",
    name: "Mountain Chalet",
    popular: true,
    facility: { rooms: 5, beds: 8, bathrooms: 3, sqft: 1800 },
    rent: 2200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306709/hotels/decorative-wooden-jacht-stands-before-picture-sea-port-wall_1304-3691_rsvxba.jpg",
    city: "Mumbai",
  },
  {
    id: 31,
    location: "Rural Retreat",
    name: "Rural Retreat",
    popular: false,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 700 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306702/hotels/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-luxury-hotel-resort_146671-18827_c1bjuq.jpg",
    city: "Paris",
  },
  {
    id: 32,
    location: "Cozy Chalet",
    name: "Cozy Chalet",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1300 },
    rent: 1700,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306697/hotels/pool-relaxation-sea-scene-nature_1203-6304_rb6iqq.jpg",
    city: "London",
  },
  {
    id: 33,
    location: "Lakeside Getaway",
    name: "Lakeside Getaway",
    popular: true,
    facility: { rooms: 4, beds: 8, bathrooms: 3, sqft: 1600 },
    rent: 2000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306693/hotels/swimming-pool_1203-3484_zbync2.jpg",
    city: "New York",
  },
  {
    id: 34,
    location: "Downtown Apartment",
    name: "Downtown Apartment",
    popular: false,
    facility: { rooms: 1, beds: 2, bathrooms: 1, sqft: 500 },
    rent: 900,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306687/hotels/admiralty-embankment-night_1398-2738_pw0pcc.jpg",
    city: "Mumbai",
  },
  {
    id: 35,
    location: "Hillside Cabin",
    name: "Hillside Cabin",
    popular: true,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306681/hotels/relaxation-pool-umbrella-lounge-sky_1203-4625_bteahn.jpg",
    city: "Paris",
  },
  {
    id: 36,
    location: "Ocean View Villa",
    name: "Ocean View Villa",
    popular: false,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1100 },
    rent: 1500,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306674/hotels/night-city-view_1417-1724_e7ncnb.jpg",
    city: "London",
  },
  {
    id: 37,
    location: "Countryside Cottage",
    name: "Countryside Cottage",
    popular: true,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 700 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306670/hotels/night-view-skyscraper-port-olimpic_1398-428_yr8yyf.jpg",
    city: "New York",
  },
  {
    id: 38,
    location: "Downtown Loft",
    name: "Downtown Loft",
    popular: false,
    facility: { rooms: 1, beds: 1, bathrooms: 1, sqft: 400 },
    rent: 800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306665/hotels/hotel-nevada-usa_1268-14393_gu9wbb.jpg",
    city: "Mumbai",
  },
  {
    id: 39,
    location: "Seaside Retreat",
    name: "Seaside Retreat",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1300 },
    rent: 1700,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306658/hotels/popular-resort-amara-dolce-vita-luxury-hotel-with-pools-water-parks-recreational-area-along-sea-coast-turkey-sunset-tekirova-kemer_146671-18759_g4jziy.jpg",
    city: "Paris",
  },
  {
    id: 40,
    location: "Mountain Cabin",
    name: "Mountain Cabin",
    popular: false,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1200,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306650/hotels/large-pool-with-umbrellas-hammocks_1203-182_qwp4as.jpg",
    city: "London",
  },
  {
    id: 41,
    location: "123 Main St",
    name: "Cozy Inn",
    popular: true,
    facility: { rooms: 4, beds: 6, bathrooms: 2, sqft: 1200 },
    rent: 1500,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259314/hotels/light-garden-luxury-pool-nature_1203-4908_cmraeb.jpg",
    city: "New York",
  },
  {
    id: 42,
    location: "222 Cedar St",
    name: "Mountain View Lodge",
    popular: true,
    facility: { rooms: 6, beds: 10, bathrooms: 4, sqft: 2200 },
    rent: 2800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306721/hotels/popular-resort-amara-dolce-vita-luxury-hotel-with-pools-water-parks-recreational-area-along-sea-coast-turkey-tekirova-kemer_146671-18757_dxdfpl.jpg",
    city: "New York",
  },
  {
    id: 43,
    location: "789 Oak Dr",
    name: "Green Valley Retreat",
    popular: true,
    facility: { rooms: 5, beds: 8, bathrooms: 3, sqft: 1600 },
    rent: 2000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259288/hotels/relax-area-resort_1150-10728_wnpqfl.jpg",
    city: "Paris",
  },
  {
    id: 44,
    location: "Beachfront Bungalow",
    name: "Beachfront Bungalow",
    popular: true,
    facility: { rooms: 3, beds: 6, bathrooms: 2, sqft: 1200 },
    rent: 1600,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306709/hotels/decorative-wooden-jacht-stands-before-picture-sea-port-wall_1304-3691_rsvxba.jpg",
    city: "Paris",
  },
  {
    id: 45,
    location: "101 Pine Lane",
    name: "Sunny Side Motel",
    popular: false,
    facility: { rooms: 2, beds: 2, bathrooms: 1, sqft: 600 },
    rent: 800,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259280/hotels/leisure-beautiful-health-garden-landscape_1203-4856_ct2gke.jpg",
    city: "London",
  },
  {
    id: 46,
    location: "Mountain Retreat",
    name: "Mountain Retreat",
    popular: false,
    facility: { rooms: 4, beds: 8, bathrooms: 2, sqft: 1600 },
    rent: 2000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306702/hotels/type-entertainment-complex-popular-resort-with-pools-water-parks-turkey-luxury-hotel-resort_146671-18827_c1bjuq.jpg",
    city: "London",
  },
  {
    id: 47,
    location: "456 Elm Ave",
    name: "Riverside Lodge",
    popular: false,
    facility: { rooms: 3, beds: 4, bathrooms: 1, sqft: 900 },
    rent: 1100,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696259308/hotels/swimming-pool-beach-luxury-hotel-type-entertainment-complex-amara-dolce-vita-luxury-hotel-resort-tekirova-kemer-turkey_146671-18726_kcljqm.jpg",
    city: "Mumbai",
  },
  {
    id: 48,
    location: "Lakeside Cottage",
    name: "Lakeside Cottage",
    popular: false,
    facility: { rooms: 2, beds: 4, bathrooms: 1, sqft: 800 },
    rent: 1000,
    image:
      "https://res.cloudinary.com/dq0ns677p/image/upload/v1696306715/hotels/sky-pool-background-swimming-travel_1203-4947_suxxt5.jpg",
    city: "Mumbai",
  },
];

export default data;
